server:
  port: 8080
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:8806/reggie?serverTimezone=UTC
#    username: root
#    password: Lan20011026
#    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    host: localhost
#    password:
#    port: 6379
#    database: 0
#  cache:
#    redis:
#      time-to-live: 3600000 #设置存活时间为一小时，如果不设置，则一直存活



reggie:
  path: E:\\reggie\\img\\

spring:
  redis:
      host: localhost
      password:
      port: 6379
      database: 0
  cache:
      redis:
          time-to-live: 3600000 #设置存活时间为一小时，如果不设置，则一直存活
  sharding-sphere:
    datasource:
      names:
        master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.52.130:3306/reggie?serverTimezone=UTC&useSSL=false
        username: Lan
        password: Lan20011026
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.52.131:3306/reggie?serverTimezone=UTC&useSSL=false
        username: Lan
        password: Lan20011026
    masters-lave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true











